### ISSUE TITLE
Implement and manage API Gateway

### ISSUE THREAD

**Issue by avishka2k** [avishka2k/lms-microservices#2]
**Service Name:** api-gateway
**Server Port:** 8080
**Dependencies:**
- Eureka Client
- Gateway
- Lombok
- Spring Boot Dev Tool (optional)

```xml
<dependency>
	<groupId>org.springframework.cloud</groupId>
	<artifactId>spring-cloud-starter-gateway</artifactId>
</dependency>
<dependency>
	<groupId>org.springframework.cloud</groupId>
	<artifactId>spring-cloud-starter-netflix-eureka-client</artifactId>
</dependency>

<dependency>
	<groupId>org.springframework.boot</groupId>
	<artifactId>spring-boot-devtools</artifactId>
	<scope>runtime</scope>
	<optional>true</optional>
</dependency>
<dependency>
	<groupId>org.projectlombok</groupId>
	<artifactId>lombok</artifactId>
	<optional>true</optional>
</dependency>
```

**Eureka config In `application.yml`**

```yaml
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    registerWithEureka: true
    fetchRegistry: true

  instance:
    preferIpAddress: true
    instanceId: ${spring.application.name}:${server.port}:${random.value}
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 10
```
