### ISSUE TITLE
Implement Course Service with CRUD Operations and Eureka Integration

### ISSUE THREAD

**Issue by avishka2k** [avishka2k/lms-microservices#5]
**Service Name:** course-service
**Server Port:** 8082
**Dependencies:**

- Eureka Client
- Lombok
- Spring Web 
- Spring Data JPA 
- Rest Repositories 
- PostgreSQL Driver 
- Spring Boot Dev Tool

```xml
<dependency>
  <groupId>org.springframework.boot</groupId>
  <artifactId>spring-boot-starter-data-jpa</artifactId>
</dependency>

<dependency>
  <groupId>org.springframework.boot</groupId>
  <artifactId>spring-boot-starter-data-rest</artifactId>
</dependency>

<dependency>
  <groupId>org.springframework.boot</groupId>
  <artifactId>spring-boot-starter-web</artifactId>
</dependency>

<dependency>
  <groupId>org.springframework.boot</groupId>
  <artifactId>spring-boot-devtools</artifactId>
  <scope>runtime</scope>
  <optional>true</optional>
</dependency>

<dependency>
  <groupId>org.postgresql</groupId>
  <artifactId>postgresql</artifactId>
  <scope>runtime</scope>
</dependency>

<dependency>
  <groupId>org.projectlombok</groupId>
  <artifactId>lombok</artifactId>
  <optional>true</optional>
</dependency>
```

**Features:** 

- Create Course: `POST /api/courses`
- Get Course by ID: `GET /api/courses/{id}`
- Update Course: `PUT /api/courses/{id}`
- Delete Course: `DELETE /api/courses/{id}`
- List All Courses: `GET /api/courses`

**Entities**

- Id
- title
- description
- lecturer
- Duration
- Level
- Language
- Format (online, in-person, hybrid)
- Credits

**Example Configuration: `application.yml`**

```yaml
server:
    port: 8082

spring:
    application:
        name: course-service
    datasource: 
        url: jdbc:postgresql://<db hostname>:<db port>/<db name>
        username: <dh username>
        password: <db password>
        driver-class-name: org.postgresql.Driver
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                format_sql: true
        database-platform: org.hibernate.dialect.PostgreSQLDialect

eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/
        registerWithEureka: true
        fetchRegistry: true

    instance:
        preferIpAddress: true
        instanceId: ${spring.application.name}:${server.port}:${random.value}
        leaseRenewalIntervalInSeconds: 5
        leaseExpirationDurationInSeconds: 10

```
