### ISSUE TITLE
Implement Enrollment Service with CRUD Operations and Eureka Integration

### ISSUE THREAD

**Issue by avishka2k** [avishka2k/lms-microservices#6]
**Service Name:** enrollment-service
**Server Port:** 8083
**Dependencies:**

- Eureka Client
- Lombok
- Spring Web 
- Spring Data JPA 
- Rest Repositories 
- PostgreSQL Driver 
- Spring Boot Dev Tool

```xml
<dependency>
  <groupId>org.springframework.boot</groupId>
  <artifactId>spring-boot-starter-data-jpa</artifactId>
</dependency>

<dependency>
  <groupId>org.springframework.boot</groupId>
  <artifactId>spring-boot-starter-data-rest</artifactId>
</dependency>

<dependency>
  <groupId>org.springframework.boot</groupId>
  <artifactId>spring-boot-starter-web</artifactId>
</dependency>

<dependency>
  <groupId>org.springframework.boot</groupId>
  <artifactId>spring-boot-devtools</artifactId>
  <scope>runtime</scope>
  <optional>true</optional>
</dependency>

<dependency>
  <groupId>org.postgresql</groupId>
  <artifactId>postgresql</artifactId>
  <scope>runtime</scope>
</dependency>

<dependency>
  <groupId>org.projectlombok</groupId>
  <artifactId>lombok</artifactId>
  <optional>true</optional>
</dependency>
```

**Features:** 

- Enroll in Course: Allow students to enroll in available courses.
- View Enrollments: Enable students to view the courses they are enrolled in.
- Drop Course: Allow students to drop a course they have enrolled in.
- (pending)Enrollment Confirmation: Send confirmation notifications (e.g., email or in-app notifications) after successful enrollment.

**Example Configuration: `application.yml`**

```yaml
server:
    port: 8083

spring:
    application:
        name: enrollment-service
    datasource: 
        url: jdbc:postgresql://<db hostname>:<db port>/<db name>
        username: <dh username>
        password: <db password>
        driver-class-name: org.postgresql.Driver
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                format_sql: true
        database-platform: org.hibernate.dialect.PostgreSQLDialect

eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/
        registerWithEureka: true
        fetchRegistry: true

    instance:
        preferIpAddress: true
        instanceId: ${spring.application.name}:${server.port}:${random.value}
        leaseRenewalIntervalInSeconds: 5
        leaseExpirationDurationInSeconds: 10

```
